#!groovy

// Generated by IBM TransformationAdvisor
// Wed Apr 10 10:17:04 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'introwas'
    mvnCommands = '--version'
    test='false'
}